# Generated by Django 5.1 on 2024-08-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta'), ('ESTRELA', 'Estrela'), ('OUTRO', 'Outro')], default='', max_length=100),
        ),
    ]
